### ISSUE TITLE
部署新应用导致新添加节点负载过高

### ISSUE THREAD

**Issue by zeusro** [AliyunContainerService/kubernetes-ops-handbook#24]
**What is your Kubernetes cluster's version**:
**你的Kubernetes版本是**:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-aliyun.1", GitCommit:"27fbcf7", GitTreeState:"", BuildDate:"2020-03-11T10:33:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**What is the scenario about this issue**:
**问题背景**:

kubernetes集群添加一个8核32G的新节点之后，部署一个高CPU密集型应用，导致该新节点CPU使用率骤增。

![image](https://user-images.githubusercontent.com/5803609/87019412-26373a00-c205-11ea-8571-ba836dcd2d46.png)

**What is the classification of the problem**:
**问题分类**:

kube-scheduler

**Does the solution already exist**:
**解决方案**:

这里要顺带了解下kubernetes的调度器算法，见

从零开始入门 K8s | 调度器的调度流程和算法介绍
https://developer.aliyun.com/article/742101

”[使用反亲和度确保每个节点只跑同一个应用](http://www.zeusro.com/2018/11/20/learn-kubernetes/)“也是一种方案

- requiredDuringSchedulingIgnoredDuringExecution

```yaml
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: 'app'
                operator: In
                values:
                - nginx-test2
            topologyKey: "kubernetes.io/hostname"
            namespaces:
            - test
```

- preferredDuringSchedulingIgnoredDuringExecution

```yaml
    affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              namespaces:
              - test
              labelSelector:
                matchExpressions:
                - key: 'app'
                  operator: In
                  values:
                   - "nginx-test2"
```
